from django.db import models
from django.conf import settings

class FinancialReport(models.Model):
    REPORT_TYPE_CHOICES = [
        ('BALANCE_SHEET', 'Balance Sheet'),
        ('INCOME_STATEMENT', 'Income Statement'),
        ('CASH_FLOW', 'Cash Flow'),
        ('CUSTOM', 'Custom'),
    ]

    type = models.CharField(max_length=50, choices=REPORT_TYPE_CHOICES)
    parameters = models.JSONField(default=dict, blank=True)
    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='financial_reports'
    )
    generated_at = models.DateTimeField(auto_now_add=True)
    data = models.JSONField(default=dict, blank=True)

    def __str__(self):
        return f"{self.get_type_display()} generated by {self.generated_by} at {self.generated_at}"