from datetime import datetime
from typing import Optional, List

from pydantic import BaseModel, EmailStr, Field


# User Schemas
class UserBase(BaseModel):
    username: str = Field(..., max_length=64)
    email: EmailStr

class UserCreate(UserBase):
    password: str = Field(..., min_length=8)

class UserRead(UserBase):
    id: int
    is_active: bool
    created_at: datetime

    class Config:
        orm_mode = True

# API Key Schemas
class APIKeyBase(BaseModel):
    key: str

class APIKeyCreate(BaseModel):
    pass  # No fields required for creation, generated by backend

class APIKeyRead(APIKeyBase):
    id: int
    user_id: int
    created_at: datetime
    is_active: bool

    class Config:
        orm_mode = True

# Session Schemas
class SessionBase(BaseModel):
    token: str

class SessionCreate(BaseModel):
    user_id: int

class SessionRead(SessionBase):
    id: int
    user_id: int
    created_at: datetime
    expires_at: datetime
    is_active: bool

    class Config:
        orm_mode = True

# Fund Details Schemas
class FundDetailsBase(BaseModel):
    balance: float
    currency: str

class FundDetailsRead(FundDetailsBase):
    user_id: int
    last_updated: datetime

    class Config:
        orm_mode = True

# Authentication Schemas
class LoginRequest(BaseModel):
    username: str
    password: str

class LoginResponse(BaseModel):
    session_token: str
    expires_at: datetime
    user: UserRead

class LogoutRequest(BaseModel):
    session_token: str

class LogoutResponse(BaseModel):
    success: bool
    message: Optional[str] = None

class APIKeyResponse(BaseModel):
    api_key: str

class SessionStatusResponse(BaseModel):
    is_active: bool
    expires_at: Optional[datetime] = None

class ErrorResponse(BaseModel):
    error: str
    detail: Optional[str] = None