# Generated by Django 5.2.10 on 2026-01-13 08:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('formula_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('expression', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormulaResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('input_data', models.JSONField()),
                ('result', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='formulas.formula')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
